services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    ports:
      - "53:53/udp" 
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80/tcp"
